### ISSUE TITLE
Error inflating class com.astuetz.PagerSlidingTabStrip

### ISSUE THREAD

**Issue by merdiano** [esl/mangosta-android#30]
com.astuetz.PagerSlidingTabStrip crashes on Android devices 7.0

java.lang.RuntimeException: Unable to start activity ComponentInfo{inaka.com.mangosta/inaka.com.mangosta.activities.MainMenuActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.astuetz.PagerSlidingTabStrip

**Comment by Chirag-iBlazing** [comment]
Yes I also get same problem with this

Please check below log

``FATAL EXCEPTION: main
                                                                    Process: inaka.com.mangosta, PID: 18375
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{inaka.com.mangosta/inaka.com.mangosta.activities.MainMenuActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class com.astuetz.PagerSlidingTabStrip
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2381)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2443)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:157)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5341)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
                                                                     Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.astuetz.PagerSlidingTabStrip
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                                                                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                        at inaka.com.mangosta.activities.MainMenuActivity.onCreate(MainMenuActivity.java:53)
                                                                        at android.app.Activity.performCreate(Activity.java:6033)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2443) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:157) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5341) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 
                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                        at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                        at inaka.com.mangosta.activities.MainMenuActivity.onCreate(MainMenuActivity.java:53) 
                                                                        at android.app.Activity.performCreate(Activity.java:6033) 
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334) 
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2443) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:157) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5341) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 
                                                                     Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
                                                                        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:572)
                                                                        at com.astuetz.PagerSlidingTabStrip.<init>(PagerSlidingTabStrip.java:148)
                                                                        at com.astuetz.PagerSlidingTabStrip.<init>(PagerSlidingTabStrip.java:106)
                                                                        at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                                        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                        at inaka.com.mangosta.activities.MainMenuActivity.onCreate(MainMenuActivity.java:53) 
                                                                        at android.app.Activity.performCreate(Activity.java:6033) 
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334) 
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2443) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:157) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5341)

**Comment by adnanSharif** [comment]
I am facing the same problem after migrating to gradle 3.2.0-alpha15

> build.gradle

`buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0-alpha15'
    }
}`

But it works fine in gradle 2.3.3

> build.gradle

`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}`

**Comment by AdarshMaurya** [comment]
The issue was resolved here
[https://stackoverflow.com/questions/47006086/error-inflating-class-com-astuetz-pagerslidingtabstrip](url)
Work around:
1. Clone/download the source from [github.com/astuetz/PagerSlidingTabStrip.git](url)
2. Copy paste the res and packages.
3. Clean project and Re-build.
